import mapMeta from '@/data/world-map.json'
import { cn } from '@/lib/utils'

export type MapPin = { name: string; lat: number; lng: number; href?: string; featured?: boolean }

/** Equirectangular projection matching public/world-dots.svg (generated by scripts/generate-world-map.ts). */
export const projectPin = (lat: number, lng: number) => {
  const { region, width, height } = mapMeta
  const x = ((lng - region.lng.min) / (region.lng.max - region.lng.min)) * width
  const y = ((region.lat.max - lat) / (region.lat.max - region.lat.min)) * height
  return { left: `${(x / width) * 100}%`, top: `${(y / height) * 100}%` }
}

/**
 * Dotted world map with pulsing pins. The dot field is a static, cacheable SVG
 * loaded via <img>; pins are absolutely positioned HTML so they can be links.
 */
export function WorldMap({
  pins,
  className,
  showLabels = false,
}: {
  pins: MapPin[]
  className?: string
  showLabels?: boolean
}) {
  const aspect = `${mapMeta.width} / ${mapMeta.height}`
  return (
    <div className={cn('relative w-full select-none', className)} style={{ aspectRatio: aspect }}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="/world-dots.svg"
        alt=""
        width={mapMeta.width * 8}
        height={mapMeta.height * 8}
        className="h-full w-full"
        loading="lazy"
        decoding="async"
        draggable={false}
      />
      {pins
        .filter((p) => typeof p.lat === 'number' && typeof p.lng === 'number')
        .map((pin) => {
          const pos = projectPin(pin.lat, pin.lng)
          const dot = (
            <>
              <span
                className={cn(
                  'absolute inset-0 rounded-full bg-brand-500/60 animate-pulse-ring',
                  !pin.featured && 'opacity-60',
                )}
              />
              <span
                className={cn(
                  'absolute inset-0 rounded-full bg-brand-600 shadow-[0_0_0_2px_white,0_0_12px_rgb(225_29_46_/_0.8)]',
                )}
              />
              {showLabels && pin.featured && (
                <span className="absolute left-1/2 top-full mt-1.5 hidden -translate-x-1/2 whitespace-nowrap rounded-full glass px-2 py-0.5 text-[10px] font-medium text-ink-800 md:block">
                  {pin.name}
                </span>
              )}
            </>
          )
          // ≥24px hit area via a transparent pseudo-element (WCAG 2.5.8) without enlarging the dot.
          const cls = cn(
            'group absolute -translate-x-1/2 -translate-y-1/2 rounded-full before:absolute before:-inset-3 before:content-[""]',
            pin.featured ? 'h-2.5 w-2.5 sm:h-3 sm:w-3' : 'h-2 w-2',
          )
          return pin.href ? (
            <a
              key={pin.name}
              href={pin.href}
              title={pin.name}
              aria-label={pin.name}
              className={cls}
              style={pos}
              // Dense minor pins are decorative for keyboard users – the country list below is the accessible route.
              tabIndex={pin.featured ? undefined : -1}
              aria-hidden={pin.featured ? undefined : true}
            >
              {dot}
            </a>
          ) : (
            <span key={pin.name} title={pin.name} className={cls} style={pos}>
              {dot}
            </span>
          )
        })}
    </div>
  )
}
